#%RAML 1.0
title: Test
version: 1
baseUri: /api/{version}
traits:
  notAlwaysPresent:
    responses:
      404:
        description:  <<param | !uppercase>> cannot be found
/file:
  description: Represents a collection of files
  /{fileId}:
    description: Represents an individual file
    is:   { notAlwaysPresent: {param : test} }
    get:
      description: Gets a file
      responses:
        200:
          description: The request completed successfully.
          body:
            application/octet-stream:
              type: file