#%RAML 0.8
#baseUri: http://mocksvc.mulesoft.com/mocks/3607bd0f-a99f-4cd7-b65b-7ba5c465072c/mocks/467ff7ec-7587-42cf-96af-d5972af580dc
baseUri: http://mocksvc.mulesoft.com/mocks/6a780ab9-27a9-4857-80e4-43a46e01369c/mocks/3607bd0f-a99f-4cd7-b65b-7ba5c465072c/mocks/467ff7ec-7587-42cf-96af-d5972af580dc
title: Connectivity Service
version: 0.1
securedBy: [cs-token]
securitySchemes:
  - cs-token:
      description: You first need to obtain an access token from Core Services (aka CS). Please, review https://github.com/mulesoft/authentication-server/blob/develop/README.md to find out how to get it. 
      type: x-token
schemas:
  - error: !include utils/error.schema
  - user: !include users/user.schema
  - users: !include users/users.schema
  - environments: !include users/environments.schema
  - config: !include configs/config.schema
  - configs: !include configs/configs.schema
resourceTypes:
  - collection:
      usage: This resourceType should be used for any collection of items
      description: The collection of <<resourcePathName>>
      is: [secured]
      get:
        description: Get all <<resourcePathName>>, optionally filtered
        responses: 
          200: 
            body:
                application/json:
                  example: <<resourcePathName>>.example 
      post:
        description: Create a new <<resourcePathName | !singularize>>
        body:
          application/json:
            schema: <<resourcePathName | !singularize>>
        responses: 
          201: 
            body:
              application/json:
                example: !include utils/created.example
          400:
            body:
              application/json:
                example: !include utils/badrequest.example
          500:
            body:
              application/json:
                example: !include utils/internalerror.example
  - member:
      usage: This resourceType should be used for any singular item
      description: Single <<resourcePathName | !singularize>>
      is: [secured]
      get:
        description: Get <<resourcePathName>>
        responses:
          200:
           body:
              application/json:
          404:
            body:
              application/json:
                example: !include utils/notfound.example
          500:
            body:
                application/json:
                  example: !include utils/internalerror.example
      put:
        description: Update <<resourcePathName | !singularize>>
        body:
          application/json:
            schema: <<resourcePathName | !singularize>>
        responses:
          202: 
            body:
                application/json:
                  example: !include utils/accepted.example
          400: 
            body:
                application/json:
                  example: !include utils/badrequest.example
          404: 
            body:
                application/json:
                  example: !include utils/notfound.example
          500:
            body:
                application/json:
                  example: !include utils/internalerror.example
      delete:
        description: Delete <<resourcePathName | !singularize>>
        responses:
          204: 
            body:
              application/json:
                example: !include utils/nocontent.example
          404: 
            body:
                application/json:
                  example: !include utils/notfound.example
          500:
            body:
                application/json:
                  example: !include utils/internalerror.example

traits:
  - secured: 
      headers: 
        Authorization: 
          type: string
          description: | 
            Used to send a valid Core Services Access Token
            Authorization: Bearer ACCESS_TOKEN
          required: true
    paged:
        queryParameters:
          start:
            type: number
            required: false
            minimum: 0
            default: 0
          end: 
            type: number
            required: false
            minimum: 1
            default: 10

/organizations:
  /{organizationId}:
    description: The organization id where the extensions and configs live
    /extensions: 
      description: Extensions available on Exchange
      is: [secured]
      get: 
        description: Get all the extensions from Exchange
        responses: 
          200:
            body:
              application/json: 
                example: !include connectors.example
      /{extensionId}:
        description: Single extension
        is: [secured]
        get: 
          description: Get a single extension from Exchange
          responses:
            200: 
             body:
              application/json: 
            404: 
              body: 
                  application/json:
                    schema: error
                    example: !include utils/notfound.example
        /versions: 
          description: Versions of this Extension
          is: [secured]
          get: 
            description: Get all the versions for the given extension
            responses: 
              200:
                body: 
                  application/json: 
                    example: !include configs/versions.example
              404:
                body: 
                  application/json:
                    schema: error
                    example: !include utils/notfound.example
          /{versionId}:
            description: Single version for the given extension
            is: [secured]
            get: 
              description: Get a single version for the given extension
              responses:
                200: 
                  body: 
                    application/json: 
                      example: |
                        {
                          "id": 9554,
                          "object_id": 71,
                          "mule_version_id": "3.7",
                          "download_url": null,
                          "doc_url": "https://docs.mulesoft.com/mule-user-guide/v/3.7/mule-paypal-anypoint-connector",
                          "feature_id": "org.mule.tooling.ui.extension.paypal-connector.3.7.0.feature.group",
                          "object_version": "3.0.1.201601191602",
                          "api_version": null,
                          "website": null,
                          "muleVersion": {
                            "id": "3.7",
                            "connectors_update_site_url": "http://repository.mulesoft.org/connectors/releases/3.5.0",
                            "doc_url": null,
                            "feature_id": null,
                            "active": true
                          },
                          "actions": [],
                          "isSuggested": true
                        }
                404: 
                  body: 
                    application/json:
                      schema: error
                      example: !include utils/notfound.example
            /configModels:
              description: Returns the config model for the given extension and its version
              is: [secured]
              get: 
                description: Get a single version for the given extension
                responses:
                  200: 
                    body: 
                      application/json:
                        example: !include configs/configModels.example
                  404: 
                    body: 
                      application/json:
                        schema: error
                        example: !include utils/notfound.example
              /{configModelId}:
                get:
                  description: |
                    Returns a configModel for a given extension 
                  responses:
                    200:
                      body:
                        application/json:
                    404:
                     body: 
                      application/json:
                        schema: error
                        example: !include utils/notfound.example
    /configs: 
      description: Configurations for the extensions
      type: collection
      get:
        responses: 
          200: 
            body:
                application/json:
                  example: !include configs/configs.example 
      post: 
        responses:
          200: 
            body: 
              application/json:
                example: !include configs/postConfig.example
      /{configId}:
        description: Single configuration for a extension
        type: member
        get: 
          responses: 
            200: 
              body:
                  application/json:
                    example: !include configs/config.example 
        put: 
          responses: 
            200: 
              body: 
                application/json:
                  example: !include configs/putConfig.example
        delete: 
          responses: 
            200: 
              body: 
                application/json:
                  example: |
                    {
                     "id": "b4df000a"                   
                    }
        /test:
          description: Test connectivity using Mule
          get: 
            responses: 
              200: 
                body: 
                  application/json:
                    schema: !include configs/test.schema
                    example: !include configs/test.example